### ISSUE TITLE
Adguard breaks GCM notifications

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1092]
Starting from the first v2.9 beta, AG messes with GCM notifications. I am not sure why (as we didn't change anything serious there), but it happens.

Here is the list of affected apps:

* Gmail
* Whatsapp
* Telegram
* etc..

**Comment by ameshkov** [comment]
> Someone reports that if he exclude Google Service Framework, the notification problem goes away

**Comment by ameshkov** [comment]
I got it, this is due to the `all ports redirect` issue

**Comment by ameshkov** [comment]
Here is what happens:
```
09:40:08.153 [pool-2-thread-1061] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=106540 Server has accepted new tcp connection. Connection info=com.google.android.gms /172.16.209.1:38967 /64.233.186.188:5228 10018
09:40:08.185 [Thread-6] DEBUG c.a.c.io.SocketPollingSelector - TCP id=106540 address=/127.0.0.1:47930 Read 184 bytes from socket channel
09:40:08.189 [pool-2-thread-1061] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=106540 Accepting incoming SSL connection
09:40:08.194 [pool-2-thread-1061] DEBUG c.a.filter.proxy.ssl.SslMitmManager - TCP id=106540 Received ClientHello:
09:40:08.208 [pool-2-thread-1061] DEBUG c.a.filter.proxy.ssl.SslMitmManager - TCP id=106540 Reusing cached SSL properties
09:40:08.210 [pool-2-thread-1061] DEBUG c.a.filter.proxy.ssl.SslMitmManager - TCP id=106540 Establishing an encrypted connection with a local client
09:40:08.212 [pool-2-thread-1061] DEBUG c.a.filter.proxy.ssl.SslProxyServer - TCP id=106540 Notify secure renegotiation true
09:40:08.213 [pool-2-thread-1061] DEBUG c.a.c.io.SocketChannelOutputStream - TCP id=106540 Write 58 bytes to socket channel
09:40:08.228 [pool-2-thread-1061] DEBUG c.a.c.io.SocketChannelOutputStream - TCP id=106540 Write 1878 bytes to socket channel
09:40:08.248 [pool-2-thread-1061] DEBUG c.a.c.io.SocketChannelOutputStream - TCP id=106540 Write 9 bytes to socket channel
09:40:08.282 [Thread-6] DEBUG c.a.c.io.SocketPollingSelector - TCP id=106540 address=/127.0.0.1:47930 Read 190 bytes from socket channel
09:40:08.297 [pool-2-thread-1061] DEBUG c.a.c.io.SocketChannelOutputStream - TCP id=106540 Write 6 bytes to socket channel
09:40:08.313 [pool-2-thread-1061] DEBUG c.a.c.io.SocketChannelOutputStream - TCP id=106540 Write 45 bytes to socket channel
09:40:08.326 [pool-2-thread-1061] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=106540 Reading HTTP request
09:40:08.390 [Thread-6] DEBUG c.a.c.io.SocketPollingSelector - TCP id=106540 address=/127.0.0.1:47930 Read 1249 bytes from socket channel
09:40:08.395 [pool-2-thread-1061] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=106540 Cannot read HTTP request Http base line violates protocol: 'À	
09:40:08.400 [pool-2-thread-1061] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=106540 Closing HTTP connection
09:40:08.404 [pool-2-thread-1061] DEBUG c.a.f.p.s.SslProxyConnectionContext - TCP id=106540 Closing SSL proxy connection
09:40:08.405 [pool-2-thread-1061] DEBUG c.a.filter.proxy.ssl.SslProxyServer - TCP id=106540 Server alert raised. Level: warning, Description: close_notify close_notify(0)
09:40:08.407 [pool-2-thread-1061] DEBUG c.a.c.io.SocketChannelOutputStream - TCP id=106540 Write 31 bytes to socket channel
09:40:08.415 [pool-2-thread-1061] DEBUG c.a.f.p.s.SslProxyConnectionContext - TCP id=106540 Closing proxy connection context
09:40:08.418 [pool-2-thread-1061] DEBUG c.a.f.proxy.TcpConnectionContext - TCP id=106540 Closing TcpConnectionContext
09:40:08.419 [pool-2-thread-1061] DEBUG c.a.f.proxy.TcpConnectionContext - TCP id=106540 TcpConnectionContext has been closed
09:40:08.420 [pool-2-thread-1061] DEBUG c.a.f.p.s.SslProxyConnectionContext - TCP id=106540 Proxy connection context has been closed
```

**Comment by ameshkov** [comment]
First of all, we should not decrypt HTTPS for ports different from 443.

**Comment by ameshkov** [comment]
Also I've changed default filtered ports list to:
`80,443,3128,3130,3143,7275,8000:49151`

**Comment by ameshkov** [comment]
Fixed

**Comment by Havock94** [comment]
Hello, I'm using AdGuard 2.12.247 on my OnePlus 5T with Android Oreo 8.1.
I'm still having issues with push notifications from Facebook, Instagram and from an app called Join (by joaoapps) that I use to share the clipboard across my devices since it uses GCM notifications.

I modified the default filtered ports but that didn't solve the issue.
As soon as I stop the AdGuard service I receive all the notifications that I was supposed to receive earlier. 

Can you please help me?
Thank you

**Comment by ameshkov** [comment]
@Havock94 as I recall, the issue with GCM is random, but it often occurs when Android connects to GCM servers over IPv6. Could you please try disabling IPv6 in the APN settings and see if there's any change?

**Comment by Havock94** [comment]
@ameshkov thanks for the reply. I checked the low level setting pref.vpn.ipv6.disable so that ipv6 won't be filtered by AdGuard.
Was that the setting you were referring to? 
If so, I'll report if that helped. Thank you!

**Comment by ameshkov** [comment]
Hm, you know, I'd say that it'd be better to **block** IPv6 instead (there's a low-level setting for that too). Otherwise, some of the ad servers connections will slip through AG.
