### ISSUE TITLE
Amazon license check hangs while doing the background check

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1121]
That's what was causing filters update issues:
https://github.com/AdguardTeam/AdguardForAndroid/issues/999

**Comment by TPS** [comment]
It checks license every filterlist update?  Why?

**Comment by ameshkov** [comment]
We use the same thread for all update checks, and that thread was blocked by amazon license check.

**Comment by TPS** [comment]
Oh, yeah, that reminds me: The `🔑 License Status > Manage Your Licenses` menu option pull up licenses only for AG-site version, not the Amazon subscription, though using Amazon version.  I'm actually not sure how to check on Amazon subscription from AG UI anymore, though I can obviously check via the _Amazon_ apps or site directly.

**Comment by Revertron** [comment]
Fixed, review AJC-CR-201

**Comment by Revertron** [comment]
Test build is here: https://www.dropbox.com/s/jyfjjlbcnajqk3i/adguard-fix1121.apk?dl=1
Please, @TPS, test it thoroughly :)

**Comment by ameshkov** [comment]
What I am concerned about is Amazon license check and refresh process.

**Comment by TPS** [comment]
@Revertron Please, can you publish through Amazon ß?  The build isn't upgrade compatible, & there's no method to export User Filters, which I don't want to lose.

**Comment by Revertron** [comment]
Hm, okay, we will release RC today.

**Comment by TPS** [comment]
Preliminary check shows this might be resolved!  Let me keep an eye on it for another day or 2, though.

**Comment by TPS** [comment]
So, this works sufficiently for Nougat/7.1.1, but not Kitkat/4.4.2. Bug reports for each OS sent under user 1122984.

**Comment by TPS** [comment]
Nevermind, I just had 10 filters manual update on Nougat/7.1.1, so I don't think this fix solves #999 entirely; report resent.

**Comment by ameshkov** [comment]
@Revertron are you sure the fix was merged? I see the very same stack trace there in the log, it is simply not possible with the fix:
```
Thread:	290	pool-1-thread-1	WAITING
-2 java.lang.Object.wait(Native Method)
2127 java.lang.Thread.parkFor$(Thread.java:2127)
325 sun.misc.Unsafe.park(Unsafe.java:325)
161 java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
840 java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:840)
994 java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
1303 java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
203 java.util.concurrent.CountDownLatch.await(CountDownLatch.java:203)
-1 com.adguard.android.service.license.f.i(Unknown Source)
-1 com.adguard.android.service.license.f.g(Unknown Source)
-1 com.adguard.android.service.license.f$1.run(Unknown Source)
-1 com.adguard.android.service.t.run(Unknown Source)
428 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
278 java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
273 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
1133 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
607 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
761 java.lang.Thread.run(Thread.java:761)
```

**Comment by ameshkov** [comment]
@TPS could you please restart AG, wait for 10 minutes and send us a new log?

I'd like to check what's going on with the amazon subscription check.

**Comment by TPS** [comment]
@ameshkov Just sent.

**Comment by Revertron** [comment]
Fixed.

**Comment by TPS** [comment]
Sent another report via today's ß, but same negative result, & additional problem of licensing issue (my ß license wasn't active in-app on update, & was only activated w/ difficulty).

**Comment by ameshkov** [comment]
@TPS what with 2.9.60? It should've been better now.

I still don't understand why in your case license check is so unstable, but at least it shouldn't cause licensing issues now.

**Comment by TPS** [comment]
It's noticeably better (@ least on Nougat/7.1.1ß, I think), but I'll keep an eye on it, & send a report soon if it seems off.

**Comment by TPS** [comment]
This works well. Thanks a bunch! 😁👏
