### ISSUE TITLE
Disabling net access for Android OS does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1498]
Screenshot:

<details>

![photo_2017-09-30_17-08-19](https://user-images.githubusercontent.com/5947035/31053613-2225dcf6-a6aa-11e7-8751-002a3afe929a.jpg)
</details>

**Comment by Revertron** [comment]
If we can not determine UID of the connection, we consider it as system connection :)
I would rather discard such connections.

**Comment by ameshkov** [comment]
> If we can not determine UID of the connection, we consider it as system connection :)I would rather discard such connections.

The further action with such connection should rely on the settings user has for the "Android OS" app.

**Comment by Revertron** [comment]
Fixed.

**Comment by ameshkov** [comment]
First of all, traffic is still attributed to Android OS.

Second issue: If 'Android OS' is disallowed net access I can surf etc. - until I enable AG DNS. Then DNS requests are blocked by AG. Enabling net access for 'Android OS' makes AG DNS filtering work.

**Comment by Revertron** [comment]
Fixed. We checked local port instead of destination port :)

**Comment by ameshkov** [comment]
It seems that this issue is not fully resolved.

Report from XDA:
https://forum.xda-developers.com/showpost.php?p=74839356&postcount=2939

> # "Android OS" previously abided by the rules on earlier 2.10.x versions. However in RC and Stable, it is Green - Red - Red, having no internet access. Why has it got 1.2GB of traffic and 120KB of blocked traffic??? If something is blocked, with SSL ticked (https filtering) then how is it allowed to transmit/receive data?

**Comment by Revertron** [comment]
We have had some bug that erroneously saved statistics for Android OS, I think after merging #1665 it will not do this anymore.

**Comment by ameshkov** [comment]
Should be re-tested, though

**Comment by ameshkov** [comment]
Fixed
