### ISSUE TITLE
Make alternate color scheme for users with color blindness

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#151]
Color blindness makes green and red very much alike.
This causes trouble, especially in Firewall section.
We should think of a way to optimize it better.

Original requester here - XOM-709-54345

**Comment by ameshkov** [comment]
Huh, never though about it this way.. We will take this into account when we'll re-design the app.

**Comment by Bohdan-SUP** [comment]
Another requester here - OKA-355-99733

**Comment by ameshkov** [comment]
Also we should take this into account (case when user is green/red colorblind):
http://forum.xda-developers.com/showpost.php?p=64526269&postcount=487

**Comment by evgeniy-ADG** [comment]
> уважаемые разработчики. у меня предложение для изменения цвета для дальтоников. в бредмаузере при включении и отключении разрешений вай фай, лте и блокировки рекламы. ничего не понятно отключил или нет. плохо отличяються оттенки. сделайте допустим красное выкл а черное вкл

**Comment by ameshkov** [comment]
Да, мы это учтем обязательно.

**Comment by TPS** [comment]
Judicious use of :no_entry_sign: over or adjacent/corner to the AG shield should perhaps answer for the red version here, perhaps?

**Comment by TPS** [comment]
@ Any1 who's following this:
___Please___ check to make sure the icons shown in https://github.com/AdguardTeam/AdguardForAndroid/issues/203#issuecomment-210406966 suit your particular colorblindness!

**Comment by TPS** [comment]
I think this is officially solved now?  Color-blind folks, if you could chime in?

**Comment by TPS** [comment]
Oops, firewall colors/shapes not solved yet!

**Comment by ameshkov** [comment]
Nah, not solved, we'll take this into account in v3.0.

What about this issue, it is about having an alternate scheme, which is even harder than simple icons color change.

**Comment by TPS** [comment]
Like #104, but for color-blind?  Doesn't also include related color-only toggles like in firewall (which perhaps could be solved like in #203 & related) & other similar problems?

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/2637
