### ISSUE TITLE
Google Backup does not work on Wi-Fi while on VPN

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1587]
Android 8.1.0 can't route Wi-Fi while on VPN. Reproduced even with **NoRoot Firewall**.

### Steps to reproduce

1. Install and enable any VPN app
2. Try to auto-backup photos in **Google Photos** or stream music in **Play Music** (`Stream only on Wi-Fi` setting must be ON)

### Expected behavior
Apps should work with no network errors

### Actual behavior
**Google Photos** can't backup any photos with `Waiting for Wi-Fi` message. **Play Music** can't stream any song with `Can't prepare radio. Please try againg.` message.

<details><summary>Screenshots and video:</summary>

![screenshot_20171113-202539](https://user-images.githubusercontent.com/28726429/32740901-7e3a9608-c8b5-11e7-8467-221c3bcd0073.png)

![screenshot_20171113-202532](https://user-images.githubusercontent.com/28726429/32740906-815ea716-c8b5-11e7-9b00-00a0b8131111.png)

**VIDEO**
https://uploads.adguard.com/up01_dj4zx_device-2017-11-13-203520.mp4

</details>

### Logs
[Archive.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1467921/Archive.zip)

### Customer ID
1656541, 1691627

### Your environment

* Adguard version: 2.10.164
* Adguard filtering mode: VPN
* Device model: Google Nexus 6P
* Android 8.1.0
* Not rooted

**Comment by ameshkov** [comment]
@altokarev report it to Google please

**Comment by altokarev** [comment]
Reported: https://issuetracker.google.com/issues/69398165

**Comment by crispinb** [comment]
The Android team in their wisdom have decided not to fix this until some 'future release'. This unfortunately makes Adguard unusable on Android. Presumably they have decided to force ads on Android users.

**Comment by ameshkov** [comment]
I wonder would it help to disable filtering for Google apps in AdGuard's apps mgmt settings?

Photos, Play Music, etc.

**Comment by crispinb** [comment]
@ameshkov Good thought -- I've never got round to exploring the Android Adguard settings. Just tried it and is promising so far. Background upload of one test photo just worked with Adguard enabled. That's not enough of a test to be certain it works under all circumstances (eg does Photos offload jobs to Google Play Services when in the background?) but looks good. Thanks.

**Comment by ameshkov** [comment]
Okay, this is not officially our bug:)

Google closed the original issue as `Won't Fix (Intended Behavior)`

> When a VPN is up the OS has no way to guarantee that network traffic will go on wifi. The VPN app could decide to send and receive traffic on any available interface, including cell data. Recent changes to the VPN code have made it so that if the VPN calls setUnderlyingNetworks, the networking APIs will reflect some of the properties of the underlying networks (e.g., whether they are metered or not) into the VPN's networkcapabilities. But it's up to the podcast app to use the required APIs, such as isActiveNetworkMetered.

**What we should do now**

On Oreo, we should be calling [`VpnService.setUnderlyingNetworks`](https://developer.android.com/reference/android/net/VpnService.html#setUnderlyingNetworks(android.net.Network[])) when the tunnel is established and [`VpnService.Builder.setUnderlyingNetworks`](https://developer.android.com/reference/android/net/VpnService.Builder.html#setUnderlyingNetworks(android.net.Network[])) when we're preparing the tunnel.

**Comment by Revertron** [comment]
Aha, and we can pass `null` to let the system know, that we are not binding to particular interface.
I think it will be easy.

**Comment by TPS** [comment]
Fair warning, FYI: If y'all read the rest of the issue thread where that last quote comes from, not even the existing official GApps implement this functionally, so perhaps not so easy/simple. 🤦🤷‍♂️🤔

**Comment by ameshkov** [comment]
> Aha, and we can pass null to let the system know, that we are not binding to particular interface.
I think it will be easy.

This is a default behavior and it does not seem to work. It is worth trying, though -- just reproduce the original issue first.

If it does not work out well and we are forced to specify the exact `Network`, don't forget that you'll also need to use `bindSocket`:

> This method only needs to be called if the VPN has explicitly bound its underlying communications channels — such as the socket(s) passed to protect(int) — to a Network using APIs such as bindSocket(Socket) or bindSocket(DatagramSocket). The VPN should call this method every time the set of Networks it is using changes.

**Comment by sviperz** [comment]
AG version: 2.11.31 Beta
AG filtering mode: VPN
Device: Google Pixel 2016
OS: Android 8.1.0
No root

Google Photos indeed doesn't "see" WiFi connection when AG is enabled.
![no_backup](https://user-images.githubusercontent.com/11470610/37294117-2d192ffe-2626-11e8-9b29-264f694ea0dd.png)

Disabling the app in the Apps Management settings fixed the issue immediately.
![backing_up](https://user-images.githubusercontent.com/11470610/37294141-3550de4c-2626-11e8-927d-767ff5608e37.png)

**Comment by ameshkov** [comment]
@sviperz it should be resolved in the latest nightly

**Comment by sviperz** [comment]
@ameshkov yes, it's fixed for now. Thanks!

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1853

looks like this issue is back

**Comment by nkartyshov** [comment]
This system problem the Android Oreo 8.1, on the Android P such problem is not observed. The Android cannot reconfigure wifi routes when the VPN works. 
Workaround is to turn off filtering for Google photos.

**Comment by Kr328** [comment]
@ameshkov 
Same problem on Android Pie but shadowsocks-android resolve it by [this](https://github.com/shadowsocks/shadowsocks-android/commit/0af450008b021592d3a1241891f593ddfbd57b15)

Call `VpnService.setUnderlyingNetworks` when default network changed and pass default `Network` to it

**Comment by ameshkov** [comment]
@Kr328 this is exactly what we do

**Comment by ameshkov** [comment]
@Kr328 thanks for the link anyway! I guess we'd better review ours just in case: https://github.com/AdguardTeam/AdguardForAndroid/issues/2836
