### ISSUE TITLE
Magisk Manager unable to pass SafetyNet check with AdGuard enabled

### ISSUE THREAD

**Issue by ianmacd** [AdguardTeam/AdguardForAndroid#1894]
### Steps to reproduce
1. Create an exception for Magisk Manager under Apps Management. Uncheck 'Enabled'. 
2. Start Magisk Manager with AdGuard enabled
3. Tap on 'Tap to start SafetyNet check'.

### Expected behavior
SafetyNet check should pass.

### Actual behavior
"The response is invalid."

4. Now disable Adguard completely.
5. Tap again on 'Tap to start SafetyNet check'.

Now Safety Net check will pass.

* Adguard version: 2.12.34
* Adguard filtering mode: Proxy (auto)
* Device model: S9+, also S3 Tab
* Operating system and version: Android 8.0
* Rooted or not? Yes

Possibly the problem is related to the fact that Magisk Manager downloads an extra package to perform the Safety Net check, and invokes this as com.topjohnwu.snet. But this plug-in cannot be found under Apps Management in AdGuard, so it is impossible to disable filtering for it.

**Comment by Revertron** [comment]
Some new data:
If I disable AdGuard and start one time SafetyNet Check, then it says "Success".
If I then enable AdGuard and filtering for Magisk, it will say "Success" again.

It seems, that our root proxy mode is interfering with installation of `snet.apk`, not connections o_O.

**Comment by Revertron** [comment]
Then, if I disable and re-enable Wi-Fi network, it will get an error again...

**Comment by Revertron** [comment]
Okay, this time I have no problems to check SafetyNet on my phone. But one thing changed - I've rebooted it yesterday.

So, @ianmacd, try to make these steps:
1. Disable AdGuard protection
2. Check SafetyNet in Magisk
3. Reboot your device
4. After reboot enable AdGuard protection
5. Check SafetyNet in Magisk once more

Does Magisk still show an error on step 5?

**Comment by ameshkov** [comment]
@ianmacd is there still an issue with this?

**Comment by Samitinjaya** [comment]
I have replicated the steps listed by @Revertron. It works fine immediately after a reboot. I was on connected to the internet on wireless when I tested that. When I switched to LTE, same error, when However when I tried after 1 hour when connected to wireless, same error  - response is invalid error. Now, I am on LTE, and turned off Adguard rebooted, turned on Adguard, checked safetynet - invalid respose - tried after 10 minutes - safety net passes. Long story short, the reboot works in a very erratic way. So yes, there is still an issue with this

**Comment by MZGSZM** [comment]
I can confirm this is an issue for me as well. AdGuard app version 2.12.247 on Android 9. My phone is the _OnePlus 5_ running the _Pixel Experience_ ROM.

It seems this affects a few other apps for me as well. 

[**Pokémon GO**](https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo): Sign in doesn't work unless AdGuard is completely disabled. Nothing is listed as blocked in AdGuard
[**Stash**](https://play.google.com/store/apps/details?id=com.stash.stashinvest): Throws an error at startup that says "Something went wrong. Please verify that you are using the latest version, then try again". Nothing shows as blocked in AdGuard and completely disabling it is the only way to get the app to work.
[**Snapchat**](https://play.google.com/store/apps/details?id=com.snapchat.android): This one behaves much in the same way as PoGO in that sign in doesn't work and an error is thrown until AdGuard has been completely disabled.

Thankfully I don't use any of these apps very often.
Let me know if there's any other information that would be helpful for diagnosing this problem.

**Thanks!**
~Nathan

**Comment by freezewind** [comment]
I confirm this in vpn mode also if I move the certificate to system store.
version 2.12.247
pixel 2 xl android 9

**Comment by MZGSZM** [comment]
> 
> 
> @MZGSZM @freezewind guys, how exactly did you move the certificate? Did you do it in AdGuard settings or using a Magisk module?

I tried to move it with the app but had no success so I used the "Move Certificates" module by "[yochananmarqos](https://forum.xda-developers.com/member.php?u=5124760)" from the Magisk repo.

**Comment by freezewind** [comment]
I also use "Move Certificates" module too.

**Comment by Xyllon** [comment]
Not sure if it worsens ad blocking, but adding googleapis.com to Settings > HTTPS Filtering > Whitelist appears to fix it.

**Comment by MZGSZM** [comment]
> 
> 
> Not sure if it worsens ad blocking, but adding googleapis.com to Settings > HTTPS Filtering > Whitelist appears to fix it.

I may have to try that, though I'd be interested to hear how that will affect ad blocking if anyone here knows.

**Comment by ameshkov** [comment]
> Not sure if it worsens ad blocking, but adding googleapis.com to Settings > HTTPS Filtering > Whitelist appears to fix it.

Hm, this is interesting! However, I'd better have HTTPS filtering d

**Comment by MZGSZM** [comment]
> 
> 
> Not sure if it worsens ad blocking, but adding googleapis.com to Settings > HTTPS Filtering > Whitelist appears to fix it.

I may have to try that, though I'd be interested to hear how that will affect ad blocking if anyone here knows.

**Comment by nkartyshov** [comment]
I disabled https filtering from app com.google.android.gms and SafetyNet check succeeds

**Comment by ameshkov** [comment]
@nkartyshov well, I guess we need to figure a way how to disable HTTPS filtering for `googleapis.com` requests sent from `com.google.android.gms`.

**Comment by ameshkov** [comment]
Maybe we should extend the current HTTPS filtering exclusions list format and allow specifying app name there?

**Comment by MZGSZM** [comment]
It appears this problem is resolved in the beta 3.0 release [3.0.241B (1.3.142cl) specifically]. I haven't been able to test it extensively, but haven't had issues with Magisk Manager being unable to check SafetyNet status since I installed this update.

**Comment by ameshkov** [comment]
Awesome, thank you for testing it!

**Comment by freezewind** [comment]
I also tried 3.0.241B, but it doesn't resolve this problem for me if I reset the HTTPs Whitelist( I added googleapis.com to Whitelist by myself ).

**Comment by ameshkov** [comment]
Well, in the current version we disabled HTTPS filtering for Google Play Services (`com.google.android.gms`). If you have enabled it manually, it will mess with the fix.

In the next build, we'll use a better solution, disable HTTPS filtering for `googleapis.com` connections which are made by `com.google.android.gms`. This type of exclusions is not yet supported in the first beta

**Comment by nkartyshov** [comment]
Added the googleapis.com domain to the ssl exclusions for the com.google.android.gms app.
Commit: https://github.com/AdguardTeam/HttpsExclusions/commit/272fd842345ca45177f6266e39dc3fce32878525
