### ISSUE TITLE
Put 'Disabled' status if Filter group is disabled

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2380]
It would be nicer this way.

<details>

![20181207_224843](https://user-images.githubusercontent.com/44832195/49669511-a2d6c500-fa72-11e8-9df4-b687454202da.jpg)

</details>

**Comment by admitrevskiy** [comment]
Resolved.

**Comment by aspasskaya** [comment]
The problem still exists.
Filters disabled, the protection restarted, but on the screen, status doesn't change. 
If go back to the previous screen and back - the status will change.
# 
https://uploads.adguard.com/assa_mj2ou.mp4
