### ISSUE TITLE
Browsing security event has wrong status in filtering log

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2512]
It is "modified" instead of "unsafe". 
Also, stats are not changed after browsing security detection.

**Comment by nkartyshov** [comment]
fixed

**Comment by karina-archazh** [comment]
![image](https://user-images.githubusercontent.com/41899455/52489106-76eed180-2bd2-11e9-8dfd-02486342cb68.png)


Still persist in 3.0.232

**Comment by nkartyshov** [comment]
The safe browsing broke in the previous CL, but it work fine with new version:
![device-2019-02-13-172212](https://user-images.githubusercontent.com/3413799/52718479-a2980000-2fb4-11e9-9737-785ad2b50273.png)
