### ISSUE TITLE
Persist the last selected statistics date range

### ISSUE THREAD

**Issue by SonyaMer** [AdguardTeam/AdguardForAndroid#2516]
### Steps to reproduce

1. Open Main page
2. Set up a period of statistics
3. Quit the app
4. User's settings will go back to "All time"

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: v3.0.220η (1.3.113cl)
* Adguard filtering mode: VPN 
* Device model: Samsung J7
* Operating system and version Android 6.0
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? no

**Comment by ameshkov** [comment]
@SonyaMer so you want us to persist the last selected stats period, right?

**Comment by SonyaMer** [comment]
Correct:)

**Comment by madasahat** [comment]
Please introduce this. I would like the time and day range to stick to my selection after returning to home page. I have submitted this but didn't realise or see this post until it was too late

**Comment by sam20e** [comment]
Following this, we really need this feature. it should not revert back to "all time" automatically.

**Comment by Revertron** [comment]
Fixed in PR 1160.

**Comment by ameshkov** [comment]
@Revertron it does not work as it was supposed to.

It does not seem to be persisted at all.

**Comment by sam20e** [comment]
@TheHasagi may I know why you closed this request? I'm running your latest version and it's not fixed yet. By default it's showing only "All time" stats. We can change this but once we close and reopen the app its going back to All Time. 

@Revertron @ameshkov  could you please check and verify this?
