### ISSUE TITLE
Infinity load then download failed

### ISSUE THREAD

**Issue by vadrozh** [AdguardTeam/AdguardForAndroid#2560]
### Steps to reproduce

1. Start an app update
2. Abort file download by system/user(for example if you have not enough space in memory)

### Expected behavior

AdGuard will stop an update.
### Actual behavior

AdGuard shows popup "Update downloading, please wait"
<details>
*forgot to get an screenshot*

</details>

### Your environment

* Adguard version: Last Stable
* Adguard filtering mode: VPN / Proxy(manual/auto): VPN
* Device model: (e.g. Google Pixel): GT-S7270
* Operating system and version (e.g. Android 7.1.2): 5.1 Cyanogenmod
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No.

**Comment by nkartyshov** [comment]
Fixed

**Comment by aspasskaya** [comment]
Disable wifi. The problem still exists. Downloading hung.
# 
![image](https://user-images.githubusercontent.com/43952607/53632375-d2d2d600-3c25-11e9-9f80-39a454c16cd3.png)
# ! Also, check filters update. Should be error.
 
![image](https://user-images.githubusercontent.com/43952607/53632878-137f1f00-3c27-11e9-8dbf-510f59a4e332.png)
# 
![image](https://user-images.githubusercontent.com/43952607/53633048-74a6f280-3c27-11e9-8f42-e51dfb331f6b.png)
