### ISSUE TITLE
[3.1.53 Nightly] Network rules do not block sometimes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2863]
I don't yet understand when exactly, please check the STR below.

### Steps to reproduce

1. Add `||graph.facebook.com` to the content blocking user filter
2. Install any app that uses Facebook SDK (for instance, Yandex Maps)
3. Run it
4. Check the filtering log

### Expected behavior
Connections to `graph.facebook.com` must be blocked.

### Actual behavior
Connections aren't blocked

**Comment by ameshkov** [comment]
Actually, it seems that the connections are actually blocked, but they are incorrectly reported as "processed" to the filtering log.

**Comment by patrickdrd** [comment]
they weren't working at all for me, for example I have this to disable tapatalk images:
`||tapatalk-logos.tapatalk-cdn.com^$image`
and no matter how many times I tried, clearing cache etc,
the images were there all the times

**Comment by SergeiShir** [comment]
I have the same issue with this version

**Comment by artemiv4nov** [comment]
Done, Fixed in next nightly.

**Comment by patrickdrd** [comment]
just tested in 161 and they still aren't blocked

**Comment by SergeiShir** [comment]
The issue was solved only partially - there still many log entrirs that show "Processed" for user-configured rules. Issue occurs for both Content Blocking and DNS rules alike.

**Comment by ameshkov** [comment]
@patrickdrd @SergeiShir guys, we need an example of a rule that does not work.

**Comment by patrickdrd** [comment]
I have posted an example
https://github.com/AdguardTeam/AdguardForAndroid/issues/2863#issuecomment-507524227
and I've sent it to you on telegram too

**Comment by ameshkov** [comment]
@patrickdrd got it, thank you!

Do you have HTTPS filtering enabled for Tapatalk?

**Comment by ameshkov** [comment]
What I mean is that this rule should not work in the case when HTTPS filtering is disabled for an app because we cannot properly detect the content type of a request. If it was working before, this was a bug.

You should change the rule to `||tapatalk-logos.tapatalk-cdn.com^`

**Comment by patrickdrd** [comment]
nope, but still 3.1.45 blocks them

**Comment by ameshkov** [comment]
> nope, but still 3.1.45 blocks them

Yep, and this was a bug actually, see https://github.com/AdguardTeam/AdguardForAndroid/issues/2863#issuecomment-508857325

**Comment by patrickdrd** [comment]
you mean convert them to network

**Comment by ameshkov** [comment]
> you mean convert them to network

Mm, I'd say wide domain-level blocking rules.

**Comment by patrickdrd** [comment]
I saw that it was working that's why I kept it, I have others similar too, if https is enabled would they work? in the future versions?

**Comment by ameshkov** [comment]
If HTTPS filtering is enabled for an app, they will work as we are able to properly detect the content type. But if HTTPS filtering is disabled, the only supported modifiers are `$app` and `$important`

**Comment by patrickdrd** [comment]
I could add the tapatalk one to the dns ones

**Comment by patrickdrd** [comment]
ok thanks I'll check them later and I'll let you know if I have to ask anything

**Comment by patrickdrd** [comment]
I found one:
what about graph.facebook that I'm blocking for many apps?
here maps for example are without https filtering

**Comment by SergeiShir** [comment]
Hi. Indeed enabling HTTPS Inspection improved the situation.

Upon closer examination of logs and rules, I only have problems with TCP and UDP connections such as tcp://www.google.com

I already enabled HTTP Inspection for Chrome. I do not have a specific rule for TCP connections to that URL. 
What confuses me is the "Processed" status in the log.

Example screenshot:
![ScreenshotCapture_2019_07_06_07_39_40_167](https://user-images.githubusercontent.com/17823400/60751662-00f46800-9fc2-11e9-8869-fafc8f839582.png)

**Comment by ameshkov** [comment]
@SergeiShir thank you for the details! I've created a new issue for this case: https://github.com/AdguardTeam/AdguardForAndroid/issues/2912

**Comment by artemiv4nov** [comment]
@SergeiShir Fixed in the latest nightly.

**Comment by SergeiShir** [comment]
The situation is much better, but there are still multiple log entries that
show tcp://
Connections were made by these apps, at least:
WhatsApp
Google Play Store
Web browser

See the attached example screenshot

**Comment by artemiv4nov** [comment]
@SergeiShir can you send me logs and screenshots, please? devteam@adguard.com

**Comment by SergeiShir** [comment]
I sent the requested files by a separate email with this subject:
Debug files for Bug 2863 - AdGuard for Android

The logs were collected with "Record everything" setting
I opened the cnn.com in Chrome browser
and opened Google Play app

**Comment by ameshkov** [comment]
Logs are in ncloud

**Comment by admitrevskiy** [comment]
@SergeiShir hi!
Please, check the latest nightly, this issue should be fixed

**Comment by SergeiShir** [comment]
AdGuard shows "No updates available" for several days already
I have v3.2.110

**Comment by SergeiShir** [comment]
Hello

Thank you for your work

There are NO logs with TCP connections for web browsing

I still see the TCP connections from these 2 apps:
Google Play Store
Google Play Services

I sent the logs and screenshots to devteam@adguard.com

The subject of that email is:
Files for Bug 2863 (AdGuard for Android)
Sent at 08:09 GMT+3

**Comment by ameshkov** [comment]
@SergeiShir this is not a bug in this case. Just TCP connections. AdGuard does not try to inspect them and detect the content type because of the $network rules you have.

**Comment by SergeiShir** [comment]
Thank you for your response

I deleted my rules

Now, the logs show the expected HTTPS

I still saw at least one log with TCP for Google Play Services app - see
the attached screenshot

**Comment by SergeiShir** [comment]
Another example of a TCP log is attached - for the WhatsApp

Is this because HTTPS Filtering is disabled for that app?

**Comment by ameshkov** [comment]
> I still saw at least one log with TCP for Google Play Services app - see
> the attached screenshot

It seems that Github does not handle email attachments well enough.

Anyways, check what's the port there. If it's not 443, that's okay.
Also, check the count of bytes sent/received ("Size" item in the filtering log). If there are none, then this is just an idle connection.

> Another example of a TCP log is attached - for the WhatsApp

No, it's just WhatsApp uses some custom protocol
