### ISSUE TITLE
Adguard and "Recent apps" menu.

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#292]
STR:
1. Open "Recent Apps" menu.
2. Close (swipe) Adguard's tile.

AR: Phone switches to title screen, "recent apps" is closed.
ER: "Recents apps" should remain opened.

Adguard 2.1.359, Android 6.0, HTC One M8.
Logs and screens - BYL-476-90442

**Comment by ameshkov** [comment]
This is done to fix a bug in Android, that was killing the app process right after removing it from Recent Apps.

We should not do it in Android 5.1+.

**Comment by ameshkov** [comment]
Done

**Comment by ChristophHeilmann** [comment]
This is still not fixed. I got the same error with Adguard 2.12.233 and Marshmallow 6.0.1

**Comment by ChristophHeilmann** [comment]
I  see the dummy intent in smali:

.method public onTaskRemoved(Landroid/content/Intent;)V
    .locals 8

    .prologue
    .line 147
    sget-object v0, Lcom/adguard/android/AdguardService;->a:Lorg/slf4j/c;

    const-string v1, "Task removed called"

    invoke-interface {v0, v1}, Lorg/slf4j/c;->info(Ljava/lang/String;)V

    .line 149
    invoke-virtual {p0}, Lcom/adguard/android/AdguardService;->getApplicationContext()Landroid/content/Context;

    move-result-object v0

    invoke-static {v0}, Lcom/adguard/android/c;->a(Landroid/content/Context;)Lcom/adguard/android/c;

    move-result-object v0

    invoke-virtual {v0}, Lcom/adguard/android/c;->s()Lcom/adguard/android/service/z;

    move-result-object v0

    .line 150
    invoke-virtual {p0}, Lcom/adguard/android/AdguardService;->getApplicationContext()Landroid/content/Context;

    move-result-object v1

    invoke-static {v1}, Lcom/adguard/android/c;->a(Landroid/content/Context;)Lcom/adguard/android/c;

    move-result-object v1

    invoke-virtual {v1}, Lcom/adguard/android/c;->f()Lcom/adguard/android/service/ProtectionService;

    move-result-object v1

    .line 154
    invoke-interface {v1}, Lcom/adguard/android/service/ProtectionService;->g()Z

    move-result v1

    if-eqz v1, :cond_1

    invoke-interface {v0}, Lcom/adguard/android/service/z;->c()Lcom/adguard/android/model/enums/NotificationIconType;

    move-result-object v0

    sget-object v1, Lcom/adguard/android/model/enums/NotificationIconType;->NONE:Lcom/adguard/android/model/enums/NotificationIconType;

    if-ne v0, v1, :cond_1

    .line 157
    invoke-static {}, Lcom/adguard/android/filtering/commons/b;->l()Z

    move-result v0

    if-nez v0, :cond_0

    .line 158
    new-instance v0, Landroid/content/Intent;

    const-class v1, Lcom/adguard/android/ui/HelperActivity;

    invoke-direct {v0, p0, v1}, Landroid/content/Intent;-><init>(Landroid/content/Context;Ljava/lang/Class;)V

    .line 159
    const/high16 v1, 0x10000000

    invoke-virtual {v0, v1}, Landroid/content/Intent;->addFlags(I)Landroid/content/Intent;

    .line 160
    invoke-virtual {p0, v0}, Lcom/adguard/android/AdguardService;->startActivity(Landroid/content/Intent;)V

    .line 163
    :cond_0
    sget-object v0, Lcom/adguard/android/AdguardService;->a:Lorg/slf4j/c;

    const-string v1, "Send a dummy intent to make service foreground again"

    invoke-interface {v0, v1}, Lorg/slf4j/c;->info(Ljava/lang/String;)V

    .line 166
    invoke-virtual {p0}, Lcom/adguard/android/AdguardService;->getApplicationContext()Landroid/content/Context;

    move-result-object v0

    const-string v1, "com.adguard.android.START_PROTECTION"

    invoke-static {v0, v1}, Lcom/adguard/android/receivers/ProtectionActionsReceiver;->a(Landroid/content/Context;Ljava/lang/String;)Landroid/app/PendingIntent;

    move-result-object v1

    .line 167
    invoke-virtual {p0}, Lcom/adguard/android/AdguardService;->getApplicationContext()Landroid/content/Context;

    move-result-object v0

    const-string v2, "alarm"

    invoke-virtual {v0, v2}, Landroid/content/Context;->getSystemService(Ljava/lang/String;)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Landroid/app/AlarmManager;

    .line 168
    if-eqz v0, :cond_1

    .line 169
    const/4 v2, 0x3

    invoke-static {}, Landroid/os/SystemClock;->elapsedRealtime()J

    move-result-wide v4

    const-wide/16 v6, 0x3e8

    add-long/2addr v4, v6

    invoke-virtual {v0, v2, v4, v5, v1}, Landroid/app/AlarmManager;->set(IJLandroid/app/PendingIntent;)V

    .line 170
    sget-object v0, Lcom/adguard/android/AdguardService;->a:Lorg/slf4j/c;

    const-string v1, "Set alarm to make the service foreground again"

    invoke-interface {v0, v1}, Lorg/slf4j/c;->info(Ljava/lang/String;)V

    .line 174
    :cond_1
    invoke-super {p0, p1}, Landroid/app/Service;->onTaskRemoved(Landroid/content/Intent;)V

    .line 175
    return-void
.end method
