### ISSUE TITLE
Scrolling issue in the filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2974]
Sometimes this is hard to scloll log up. Look the video below.
Also, when you look a log in the middle of the list, it is not standing still, if some app makes  requests at that time.

### Steps to reproduce

1. Visit any site
2. Open filtering log
3. Try to scroll up

Video
[20190731_002147.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3449022/20190731_002147.zip)

### Actual behavior
It is not simple to scroll up.

### Your environment
* Adguard version: 3.2.118n
* Device model: Sony XZ1c
* Operating system and version: Android 9
* Root access:  No

**Comment by ameshkov** [comment]
Assigned to v3.3. If a bug makes it harder to create new filter rules, it should be solved asap :)

**Comment by admitrevskiy** [comment]
Done.

**Comment by Alex-302** [comment]
An issue still exists. For example, with this app:
https://play.google.com/store/apps/details?id=com.dwarfplanet.bundle
install it, scroll filtering log in the middle and just look.

Why these requests are not sorted by the time?
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/69873052-f2378600-12bf-11ea-8db8-1c37d3b60dc2.png)

 </details>

**Comment by Revertron** [comment]
The sorting maybe related to the time when that connection closes.
