### ISSUE TITLE
[Bug] [Android TV] Overlayed hints can't be dismissed; 

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#2979]
The tips that appear as overlays on the latest version (v.3.2b) are not dismissable on Android TV (Oreo, Mibox3) because you cannot interact with the "dismiss hints" button via DPAD. 

Even doing a "back" doesn't dismiss them (e.g. on "Filters" page), but takes you back to the previous page. When you go to that page again, you still see the overlay, and you're in an endless loop of just seeing greyed out screens.

**Comment by ameshkov** [comment]
@Revertron this must be addressed in v3.2.

At least the "back" button should dismiss them.

**Comment by oroboros** [comment]
> @Revertron this must be addressed in v3.2.
> 
> At least the "back" button should dismiss them.

Agreed. ATM any input via DPAD (back, button press, up/down, etc) commands what's beneath the overlay but the overlay stays and can't be dismissed. If you need more input, let me know!

**Comment by oroboros** [comment]
v.3.2.1211B

It still shows up on certain screens with no possibility to dismiss. For example in "content blocking", there's no way to neither dismiss nor access the settings on this page.
