### ISSUE TITLE
Soft reboots in Android 10

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3096]
## Issue Details

- **AdGuard version:**
  - 3.2.150
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 3
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

AdGuard should remain stable while filtering ads in the background

### Actual Behavior

AdGuard starts crashing after updating to Android 10

### Logs

See helpdesk ID 2077749

**Comment by akmLaVx** [comment]
The issue can be reproduced across a wide range of devices running Android 10. We will update the ticket with more cases.

**Comment by AnisKhanUK** [comment]
I have a Pixel 2 and can confirm the crashing as well.

**Comment by USAPaulQ** [comment]
Someone in an AdGuard forum suggested turning off app filtering so I turned off "Block Ads in All Apps" (SETTINGS > CONTENT BLOCKING...).

My phone did not reboot for two days. That's very good. I had to shut down my phone to install a new screen protector so it was only two days but it used to reboot every 36 hours or so. I will continue to leave this setting off. If I make it to Wednesday with no reboots, this setting is definitely part of the problem. (It's Sunday now)

**Comment by TheHasagi** [comment]
@AnisKhanUK @USAPaulQ 


Guys, can you go to the AdGuard - Settings - Advanced - Low-level settings - try to check the reboots with disabled pref.vpn.disable.reconfigure/pause. It would help us a lot with any results you can provide.

**Comment by ameshkov** [comment]
This issue is caused by a bug in Android's new VPN API: https://issuetracker.google.com/issues/141188490

The problem is that this API is crucial to AdGuard (and any other VPN app actually).
Once it's resolved by Google, reboots will go away.

**Comment by TheHasagi** [comment]
Update*

The problem is found. It is in Android 10, for more details follow this [link](https://at.e-tjanster.1177.se/samlsps)

**Comment by ameshkov** [comment]
The fix is currently on review in AOSP: https://android-review.googlesource.com/c/platform/frameworks/base/+/1129013

Hopefully, we'll get it with the next Android patch.

**Comment by USAPaulQ** [comment]
> @AnisKhanUK @USAPaulQ
> 
> Guys, can you go to the AdGuard - Settings - Advanced - Low-level settings - try to check the reboots with disabled pref.vpn.disable.reconfigure/pause. It would help us a lot with any results you can provide.

Do you still want me to do this even though messages after this cite a Google VPN issue? 

If so, do you want me to turn content blocking back on before I do it?

**Comment by ameshkov** [comment]
@USAPaulQ no, this won't help for sure:( It can only be fixed by Android devs.

Btw, the fix is already merged to the AOSP master branch so there's a good chance it will be included in the next patch.

**Comment by USAPaulQ** [comment]
Ok. I've left "block ads in all apps" off and the reboots have stopped. Really limits functionality but it's okay for now. I'm looking forward to the fix! Thanks!

**Comment by AnisKhanUK** [comment]
Hello, I have had the Oct 2019 patch for my Pixel 2 on Android 10.  Was this meant to have fixed the problem?  Unfortunately, my phone is still crashing.  Should I try "block ads in all apps"?

Thanks for your help.

**Comment by USAPaulQ** [comment]
> Hello, I have had the Oct 2019 patch for my Pixel 2 on Android 10. Was this meant to have fixed the problem? Unfortunately, my phone is still crashing. Should I try "block ads in all apps"?
> 
> Thanks for your help.

I don't work for AdGuard but - yes. Turn off "block ads in all apps" and it will probably stop the rebooting. The Oct 2019 patch did not solve the problem. AdGuard told me we just have to wait for the fix from Google. AdGuard is limited when you turn that off.

**Comment by artemiv4nov** [comment]
@AnisKhanUK @USAPaulQ 
That's right. Unfortunately, the Oct 2019 patch doesn't have any fixes related to the device's reboot.
But we improved the detection of open connections in AdGuard on Android. The new feature is available in the latest nightly. We will appreciate it if you can check and give feedback.

**Comment by akmLaVx** [comment]
Any updates on this one?

**Comment by kranix0** [comment]
Turning off "block ads in all apps" has not helped me. I see some improvement from disabling Adguard DNS. Reboots are now on a 2-3 day basis instead of daily. I've sent detailed logs to AdGuard.

**Comment by AnisKhanUK** [comment]
Nov Patch also doesn't seem to have fixed it - reboots continue.

Will try the disabling the DNS option.

**Comment by USAPaulQ** [comment]
Someone on Android Central also posted that Nov patch didn't solve problem. I haven't reinstalled. Waiting for stability. Haven't given up.

**Comment by ameshkov** [comment]
Hi all, there is no need in AdGuard logs, this is a known bug in the VPN API in Android 10.

The fix was already made and merged into Android code. Unfortunately, they don't tell when exactly they will ship this fix to users. Apparently, it was not shipped with the November security patch:(
