### ISSUE TITLE
Adguard enable doesn't survive Lock with WiFi off.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#36]
More details here:
http://forum.adguard.com/showthread.php?6686-Adguard-enable-doesn-t-survive-Lock-with-WiFi-off

**Comment by Revertron** [comment]
This issue must be fixed with issue #2. Therefore, I'm closing this one as duplicate.

**Comment by ameshkov** [comment]
I am pretty sure this issue won't be resolved by simply fixed #2.
Please read the details.

**Comment by Revertron** [comment]
This issue was fixed in commit 20619.
We had wrong checking of enabled state of NetworkReceiver.

**Comment by ameshkov** [comment]
The bug is still here:
http://forum.adguard.com/showthread.php?6686-Adguard-enable-doesn-t-survive-Lock-with-WiFi-off&p=65776&viewfull=1#post65776

Let's wait for logs.
