### ISSUE TITLE
google.com ping

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdguardForAndroid#3665]
https://github.com/AdguardTeam/AdguardFilters/issues/64616
 
### Background

Every google search result has a ping attribute, which opens an intermediate URL and pings google whenever it is clicked.

This extra page load really affects browsing experience on mobile, and they even have javascript code (shown in this issue https://github.com/uBlockOrigin/uAssets/issues/7960) that changes the URL when you try to copy it by long-pressing a search result.

### Current Situation

This behaviour was taken care of by the rule `www.google.*#%#//scriptlet('remove-attr', 'onmousedown|data-mousedown|ping|data-click', 'a[href][onmousedown], a[href][ping]')`. This rule however does not work in the new Samsung Internet (Beta and Normal version 13.0.1.64), but works fine with chrome. Please take a look that the screenshots in the mentioned issue, and help me point out why it is not working with Samsung Internet.

Adguard Version: 3.5.1

**Comment by AdamWr** [comment]
Probably related to this issue - https://github.com/AdguardTeam/CoreLibs/issues/1381

**Comment by sfionov** [comment]
And also related to this: https://github.com/AdguardTeam/CoreLibs/issues/1233

**Comment by zzebrum** [comment]
@cantunborn  the problem should be fixed in the release v3.6. Can you check it please once the new version is released?

**Comment by cantunborn** [comment]
Not fixed. Working with Chrome 87.0.4280.86, not working with Samsung Internet Beta 13.2.1.14. 

Probably due to JS rules not working with the new Samsung Internet, because it works fine with Samsung Internet 11.

Adguard Version: 3.6 Beta 1

**Comment by sfionov** [comment]
This problem was fixed in AdGuard CoreLibs 1.7.151.
3.6 beta 1 has CoreLibs 1.7.150.
Please try on release version.

**Comment by cantunborn** [comment]
3.6 release has not been pushed to release channel it seems, it's still on 3.6 beta 1.

**Comment by zzebrum** [comment]
@cantunborn the release should be rolled out this week
