### ISSUE TITLE
every network state change requires Adguard disable/re-enable

### ISSUE THREAD

**Issue by brokenalarms** [AdguardTeam/AdguardForAndroid#4239]
Took me a while to figure this out; I thought my phone was broken. Happens straight after a clean reformat of my phone (Pixel 5).

Any change of network from WiFi to cell or vice versa, disables Internet connectivity. All sites time out until I stop and start Adguard. Looks like it just doesn't restart the VPN tunnel through the new network.

I've read somewhere that this may be due to DNS filtering - have tried changing to Adguard DNS, but identical results. I have now disabled DNS filtering and will add here if that fixes it, but lodging this in the meantime as it's kind of a major issue whether it's just DNS or not. Thanks!

**Comment by maxikuzmin** [comment]
@brokenalarms there used to be a similar problem, but we fixed it. Now it does not occur. Could you please unload the settings and email them to devteam@adguard.com?

**Comment by maxikuzmin** [comment]
@brokenalarms "after a clean reformat" do you completely format the phone regularly?

**Comment by brokenalarms** [comment]
Yes, after phone reformat the issue persists. Settings sent.

**Comment by maxikuzmin** [comment]
@brokenalarms the network status check changes are already there in nightly and production version 3.6.10 
Have you updated to version 3.6.10?

**Comment by brokenalarms** [comment]
Confirm it still happens identically with the latest Adguard. Need to
switch on/off every network state change.

**Comment by maxikuzmin** [comment]
@brokenalarms to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@brokenalarms any news?

**Comment by brokenalarms** [comment]
Traveling currently, will update in a few days.

**Comment by maxikuzmin** [comment]
@brokenalarms what about debug logs?

**Comment by rampolino** [comment]
Same here, after deactivating adguard everything is fine. Every changing network internet is gone.

**Comment by maxikuzmin** [comment]
@rampolino are you also having any network change from wifi to cellular or vice versa disconnect your internet connection?
Does disabling/enabling AdGuard further help you?

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@rampolino any news?

**Comment by maxikuzmin** [comment]
@rampolino @brokenalarms  I am closing the issue. If the problem occurs again, you can reopen the issue
