### ISSUE TITLE
Can't install add-ons on Firefox android

### ISSUE THREAD

**Issue by clock33** [AdguardTeam/AdguardForAndroid#4242]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✓ ] I am running the latest version
- [✓ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  v.3.6.10
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Redmi Note 11 Pro 5g
- **Operating system and version:**
  -  Android 11
- **Root access:**
  -  No

### Expected Behavior

 I cannot install add-ons if I install adguard root certificate

### Actual Behavior

  Add-ons installed successfully

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_2022-09-16-11-47-05-713_org mozilla fenix](https://user-images.githubusercontent.com/60422254/190545897-e61e6811-288c-4e90-b647-dcd5859faca1.jpg)

</details>

**Comment by maxikuzmin** [comment]
@clock33 issue has been resolved. Please check adding extensions. If there are any problems you can reopen the issue

**Comment by clock33** [comment]
Hey there, sorry for delay, I just checked adding extensions. But, nope still failed..

**Comment by clock33** [comment]
> @clock33 issue has been resolved. Please check adding extensions. If there are any problems you can reopen the issue

@maxikuzmin hey there sorry for delay, I just checked adding extensions, but nope still failed to install extension..
