### ISSUE TITLE
Removed HTML element and related rule are not displayed in the request details 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#4429]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 4.0.570

### Environment

```markdown
- OS: 8.0
- Device: huawei RNE-L21
- Firmware:arm64-v8a
```

### Root access

- [ ] Yes, I have it.

### Issue Details

1: can,t import local path filter 
<details><summary>Screenshot</summary>

![Screenshot_20230207-105829](https://user-images.githubusercontent.com/41585567/217215258-98040653-13d9-4141-8bf9-b960929ab23c.jpg)
storage/emulated/0/adblocking/privacy/private/personal-v2.txt

</details>

2: log query not display html element removed and rules 

<details><summary>OLD:</summary>

![Screenshot_20230207-083308](https://user-images.githubusercontent.com/41585567/217215492-6497ddf0-d5ab-42e6-83ec-70d09717c4b4.jpg)

</details>

<details><summary>NEW:</summary>

![Screenshot_20230207-110130](https://user-images.githubusercontent.com/41585567/217215591-657549fc-4863-4f7d-9bd3-06fcf6ea0abc.jpg)

</details>

3: text overlapse https:// and /

4: package android OS missing app management

5: infinite load filter and filter dns update 

<details><summary>Screenshot</summary>

![Screenshot_20230207-105447](https://user-images.githubusercontent.com/41585567/217215914-8b9fa9c2-5cbf-4cf3-9a37-f04b18f00cee.jpg)

</details>

**Comment by Versty** [comment]
@Disqu3-mirOir-qt Hi! 

3. Should be fixed in the latest nightly (4.0 nightly 46)
4. Could you describe in detail what you mean by that?  
5. Please disable Dns protection and check for updates again. Does the issue persist?

**Comment by Disqu3-mirOir-qt** [comment]
5: caused by custom filter all custom dns and filter
4: ![Screenshot_20230213-000455.jpg](https://user-images.githubusercontent.com/41585567/218342789-3766b67f-5aa2-4a0f-919f-eaac14df4282.jpg)

this package missing firewall in v3 this package exist

**Comment by Versty** [comment]
@Disqu3-mirOir-qt Could you to provide full setting set and logs from your device to help us investigate? 

Please follow the steps below to properly collect debug logs and settings: 
1. Open AdGuard and go to Settings tab -> General.
2. Choose "Advanced".
3. Set Logging level to "Debug". It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the issue (click the update button on Home screen and wait a bit), then return to "Advanced" and set the logging level back to "Default". Notice the exact time when it happened. 
5. Use the "Export logs and system info" option to save the log file to the phone storage 
6. Go back to the Settings tab 
7. Click the context menu in the top right corner -> Export 
8. Attach both files to the email and send it to `devteam@adguard.com`, mention the issue number `#4429` in the subject and time when the issue was reproduced.

**Comment by Disqu3-mirOir-qt** [comment]
done i send mail with files thanks

**Comment by Versty** [comment]
@Disqu3-mirOir-qt Does the updates issue persist on the latest nightly?

**Comment by Disqu3-mirOir-qt** [comment]
@Versty hi in my side all fixed (update) exept issue 1 and issue 2

**Comment by Versty** [comment]
@Disqu3-mirOir-qt We discussed bringing back the ability to add a custom filter manually by path and decided it would be more convenient to use the `Browse' button instead. Therefore we suggest you to create a separate feature request and let other users vote.   

About displaying HTML element and other blocking rules. This behaviour will be improved in the future versions.

**Comment by Versty** [comment]
@Disqu3-mirOir-qt Hi! 
Could you enable the `Log removed HTML events` option in the *Settings -> General -> Advanced -> Low-level settings* and reproduce the issue? Is the removed HTML element now shown in the request details?

**Comment by Disqu3-mirOir-qt** [comment]
> @Disqu3-mirOir-qt Hi! 
> Could you enable the `Log removed HTML events` option in the *Settings -> General -> Advanced -> Low-level settings* and reproduce the issue? Is the removed HTML element now shown in the request details? 



already enabled between long time same issue see screenshot OLD and NEW

![Screenshot_20230403-165401.jpg](https://user-images.githubusercontent.com/41585567/229547311-40eac855-93e7-4755-a3a8-42a38b40e7b0.jpg)

**Comment by Disqu3-mirOir-qt** [comment]
![Screenshot_20230403-165433_1.jpg](https://user-images.githubusercontent.com/41585567/229547505-060935b1-b591-4836-8eb5-0ddc02b5d17d.jpg)

**Comment by Disqu3-mirOir-qt** [comment]
OLD ![217215492-6497ddf0-d5ab-42e6-83ec-70d09717c4b4.jpg](https://user-images.githubusercontent.com/41585567/229547738-a6029cf1-3c63-4abc-a479-50f59b0ea989.jpg)
