### ISSUE TITLE
After disabling Proxy, the traffic information through Proxy continues to be shown in the bar

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4545]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: 10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

Go to Settings tab -> Filtering -> Network -> Proxy -> Proxy server -> Add proxy server 

Turn on Proxy -> in the notification bar you can see the information about the turned on Proxy
Turn off Proxy -> you can still see the information about Proxy enabled in the notification bar

### Expected Behavior

The text in the notification bar changes depending on the state of the Proxy

### Actual Behavior

The text in the notification bar does not change depending on the state of the Proxy, it always says that the Proxy is working

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-03-28-17-10-17-434_com Slack](https://user-images.githubusercontent.com/101641415/228269612-82ce094c-5d23-49bb-a2f0-ec823a74079d.jpg)

</details>

**Comment by cjmaxik** [comment]
Isn't fixed / regression as of Nightly 78

![Screenshot_20230331_190330_Chrome](https://user-images.githubusercontent.com/1501705/229172132-ee287aaa-f020-4af0-b6fb-2467e1ff4739.png)

**Comment by maxikuzmin** [comment]
@cjmaxik should be fixed in the next nightly update

**Comment by Versty** [comment]
This issue still exists in the nightly 97.

Device info:
Android 13, SCG09
