### ISSUE TITLE
Infinite loader when sharing a video from Youtube app 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4708]
### Details 
Infinite loader when trying to watch videos from the YouTube app in AdGuard via the share button 

### Steps to reproduce 
1. Launch AdGuard 
2. Enable protection 
3. Launch Youtube application, then open any video 
4. Click the `Share` button 
5. Select AdGuard as the share option 

### Expected 
Video is playing successfully 

### Actual result 

Infinite loader is displayed 

<details><summary>Original text</summary> 
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard Version 4.0 Nightly 106

### Environment

```markdown
- OS: Android
- Device: Samsung Phone & Tablet
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Should play the video when sharing youtube videos in Adguard

### Actual Behavior

Just shows blank loading Sctlyreen in Adguard Nightly.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

</details>

**Comment by Batman2814** [comment]
It can work on iPad with Adguard so the issue is with Adguard Android Nightly. Not Google's end.

**Comment by Versty** [comment]
@Batman2814 Hi! 
Most likely one of the filters causes this issue. Could you collect the debug logs for further investigation? 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Sent this file to devteam@adguard.com:
      - mention the `4708` number in the subject
      - specify the exact time when the issue occurred

**Comment by Batman2814** [comment]
Logs sent

**Comment by Batman2814** [comment]
I'm still not able to block YouTube ads with Adguard Version 4

**Comment by Eugene-Savenko** [comment]
> Sharing a video from YouTube to AdGuard for Android to remove ads no longer works. When video is shared, AdGuard launches video player, but then video doesn't play. It just sits there hourglassing. Play and skip buttons do nothing. I'm seeing same behaviour on multiple devices with multiple videos.

Logs in CRM: 768881

**Comment by Eugene-Savenko** [comment]
> YouTube videos are not playing in the YouTube ad blocker and it happened weeks ago, But It works fine in another old phone

CRM ID: 770211

**Comment by AleksandrKalininAdGuard** [comment]
> I really love your product,  but lately,  adguard won't play YouTube videos. I have an active subscription and am using a Samsung Galaxy S8. 

CRM ID: 769723

**Comment by Versty** [comment]
@Batman2814 This issue should be fixed in the latest AdGuard for Android 4.1 nightly as a part of https://github.com/AdguardTeam/AdguardForAndroid/issues/3932. 
Could you confirm that the issue is gone on your device?

**Comment by Batman2814** [comment]
No, the issue is still here. I just updated the Nightly version from the stable version. The issue is not fixed as it says it is the release of the Nightly version of 4.1 Nightly 5.

**Comment by Batman2814** [comment]
Sent logs file again on Adguard for Android Nightly Version 4.1 Nightly 6.

**Comment by Batman2814** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/assets/96619913/b5a9dfd4-a880-4817-9062-00d0fc366b3d

AdGuard For Android Version 4.1 Nightly 11

**Comment by ihurin** [comment]
+1 CRM 772524

**Comment by VladisLoveZh** [comment]
+1 CRM 773243

**Comment by Batman2814** [comment]
Any News on when this will be fixed?

**Comment by PavelParkhomenko** [comment]
+1 CRM 778191

**Comment by ihurin** [comment]
+1 CRM 779018

**Comment by Batman2814** [comment]
What does this mean? +1 CRM 779018
Adguard is still not able to block YouTube ads in the Adguard player even though I'm now on Adguard Version 4.2 Nightly 1 and eas told it would be fixed in version 4.1

**Comment by Eugene-Savenko** [comment]
That means that there's another similar case from a different (probably) user in our helpdesk CRM system. That number is a number of a support ticket.

**Comment by Batman2814** [comment]
But 4.1 in Nightly is now Adguard 4.2. So it's not fixed.

**Comment by WagsFTW** [comment]
Adguard 4.1 Beta 1 

Still not working

**Comment by Versty** [comment]
@WagsFTW Thank you for letting us know.

What version of Android are you using?

**Comment by WagsFTW** [comment]
Android 13 TQ3A.230705.001 Google Pixel 6a
 
 
  On Sat, Jul 22, 2023 at 11:10 AM, ***@***.***> wrote:   


@WagsFTW Thank you for letting us know.

What version of Android are you using?

**Comment by Versty** [comment]
@WagsFTW Thanks! Will be fixed

**Comment by Batman2814** [comment]
It also happens on Samsung Phone Android 13. Not working

**Comment by Versty** [comment]
@Batman2814 Thank you. 
Working on the solution, will be available soon.

**Comment by Batman2814** [comment]
Adguard V4.2 Nightly 5 is working for blocking YouTube ads now.

**Comment by WagsFTW** [comment]
CONFIRMED WORKING!!! EXCELLENT JOB ADGUARD TEAM!!!! THANK YOU!
 
 
  On Sat, Jul 22, 2023 at 11:29 AM, ***@***.***> wrote:   


@Batman2814 Thank you.
Working on the solution, will be available soon.

**Comment by Batman2814** [comment]
I'm getting this problem with AdGuard Adblocker for Android Nightly when sharing a YouTube video https://youtu.be/1YwIAh4D9Xs?si=OwR8qawrlEZxj984
Where it won't block ads or play the video.
