### ISSUE TITLE
V2rayn socks5 proxy usage on Wi-Fi  leads to ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by Mioscout** [AdguardTeam/AdguardForAndroid#4816]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS:android 13
- Device:Mi 13
- Firmware:Miui China 14.0.29
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Disable WebRTC, Block Push API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:

1.Add  working proxy (V2rayn,not clash)
2.Enable proxy(disable udp routing)
3.connect wifi

### Expected Behavior

Browser should open websites

### Actual Behavior

some website can`t open,report err_connection_closed,like zhihu.com 
no same problem in 4G

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-06-21-21-30-03-354_com microsoft emmx](https://github.com/AdguardTeam/AdguardForAndroid/assets/61075611/52061566-20cd-490a-bcce-bcda85d99f6e)
![Screenshot_2023-06-21-21-30-17-490_com microsoft emmx](https://github.com/AdguardTeam/AdguardForAndroid/assets/61075611/58b2a2bc-b590-4bd7-8a7a-ec23e313cb7f)

### Additional Information

Local VPN + V2rayn Socks5 proxy + Wi-Fi network

Probably related to https://github.com/AdguardTeam/AdguardForAndroid/issues/4769 and https://github.com/AdguardTeam/AdguardForAndroid/issues/4808

**Comment by Versty** [comment]
@Mioscout Hi! 
This issue should be fixed in the latest AdGuard For Android 4.1 nightly. Could you check on your device?

**Comment by Mioscout** [comment]
> @Mioscout Hi! This issue should be fixed in the latest AdGuard For Android 4.1 nightly. Could you check on your device?

I check it on 4.1 night7,but problem still

another website has same problem is jianshu.com

**Comment by Versty** [comment]
@Mioscout We would like to take a look at the logs from your device. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Sent this file to devteam@adguard.com:
      - mention the `4816` number in the subject
      - specify the exact time when the issue occurred

**Comment by Mioscout** [comment]
> @Mioscout We would like to take a look at the logs from your device.
> 
>     1. Enable debug logging:
>        _Settings -> General -> Advanced -> Logging level -> Debug_
> 
>     2. Reproduce the issue, then remember the exact time when it happened
> 
>     3. Collect logs:
>        _Settings -> General -> Advanced -> Export logs and system info_
> 
>     4. Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
>        
>        * mention the `4816` number in the subject
>        * specify the exact time when the issue occurred

log send already,and in night 8 ,If  stop the proxy ,problem solved,open the proxy ,problem come back,sometimes edge don`t have problem but firefox still gets wrong

**Comment by yoshyv** [comment]
experienced same issue and it's a dns issue.
try turning off dns filter.

**Comment by Mioscout** [comment]
> @Mioscout Got the logs from you. Could you recall the time when the issue was reproduced?

before I send log，in one hour

**Comment by Mioscout** [comment]
> experienced same issue and it's a dns issue. try turning off dns filter.

its useful
thanks

**Comment by sfionov** [comment]
@Mioscout @yoshyv Does these sites open correctly if you disable "Protect from DPI"?

**Comment by sfionov** [comment]
@Mioscout @yoshyv Any news?

**Comment by yoshyv** [comment]
I'm not using Android currently and I don't remember this DPI protection option back then so I was using the default setting (off I assume)

**Comment by GalaxyAlpha** [comment]
> @Mioscout @yoshyv Do these sites open correctly if you disable "Protect from DPI"?

After turning off DPI in version 4.2, the problem still exists, and sometimes the website can be opened normally in very few cases.

**Comment by Versty** [comment]
@GalaxyAlpha @Mioscout @yoshyv 
The problem should be gone in AdGuard for Android version 4.4. Could you please retest and let me know the results?

**Comment by Mioscout** [comment]
> @GalaxyAlpha @Mioscout @yoshyv这个问题应该在Android版本4.4的AdGuard中消失。你能重新测试一下并告诉我结果吗？

In my device,This problem is over
