### ISSUE TITLE
Make an option to disable splash screen on Adguard launch

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#490]
In advanced options: pref.splash.enabled. Default: true.

**Comment by Revertron** [comment]
Done.

**Comment by jccube** [comment]
Ad guard splash screen still a problem. please provide option to disable.

**Comment by Revertron** [comment]
We've changed the behavior of the splash screen to be like in Google's apps.
It is shown only when the initialization of service layer is needed, i.e. when the app is not running at all (or killed by system). The second and next starts you supposed to not see it at all.

**Comment by ameshkov** [comment]
@jccube 

1. You can add comments to closed issues, there's no need to create a new one.
2. In the version v2.12 there is already a switch for the splash screen
3. This switch was removed in v3.0 beta because the current behavior is equal to having the splash screen disabled.
4. The splash screen cannot be completely disabled because of it's nature.

There will be anyway a second when the app is initializing, and at that moment Android will have to show you something. If there's no splash screen, it will be simply an empty white screen.

So the question is what exactly do you want us to do? Provide a switch that will force the "white screen" splash screen instead of the normal splash screen?

Is there any example of the behavior you want us to implement?

**Comment by jccube** [comment]
Well my friend I don't understand your rational with respect to the service
layer you mentioned. When I boot up my system, I do expect the splash
screen to reappear unless I explicitly manage to request it. The same
behavior as say google mail etc.. The splash screen should only show up in
the following use cases:

1 - When I first install the application, in order to set preferences,
options, etc..
2 - When I right-click the icon on the taskbar and manipulate settings
relevant to the application.

When you mention "initialization of the service is needed" let's be very
specific on this matter. What do you mean by this??

Do you mean a background service?? Please advise.

Jim Colmenero, B.Eng, M,Eng, Software Architect




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
02/18/19,
3:33:03 AM

**Comment by jccube** [comment]
And BTW I am referring this request specifically on the windows platform e.g. windows 10. I believe I filed my request under the proper platform. 

Regards

**Comment by ameshkov** [comment]
Ah, that was about Windows! Sorry for that, I've misunderstood it completely.

**Comment by jccube** [comment]
It is understandable. That is why we are conversing on the issue. To clear things up.
