### ISSUE TITLE
Add custom DNS server option broken

### ISSUE THREAD

**Issue by Glassertje** [AdguardTeam/AdguardForAndroid#5183]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

```markdown
- OS: Android 14
- Device: Samsung S23+ One UI 6.0
```

### Root access

- [ ] No.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Dutch filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. I click add DNS server
2. I copy/paste my 2 domains. I tried DoH, DoT and DoQ
3. i get a red message that server isn't responding or not exist

### Expected Behavior

That the added servers are working. As it was in app version 4.2 and before.

### Actual Behavior

If i add these in the custom DNS field i get a red message that server isn't responding or not exist.

### Screenshots

<details><summary>Screenshot 1:</summary>

<![vb](https://github.com/AdguardTeam/AdguardForAndroid/assets/114856327/dbc49269-e954-406c-ac33-641bedd3ec58)>

</details>

### Additional Information

I have 2 AGH installs with 2 domain names. If i add these in the custom DNS field i get a red message that server isn't responding or not exist. In Android version 4.2 and before, it works flawless. I just tested in app version 4.2 and DNS is working. So something is broke. I also tested the latest nightly but also not working. 

Sometimes i can add my 2 servers, but then after a while i don't have any internet. 

I can provide you the 2 domains, but not public. 

I also send a support ticket 864038, i have send 2 debug logs to the ticket email. 1 from version 4.2 and the other is 4.3.1. I want to ask if you gonna reveal any kind of log, to hide the 2 domains. Be course I don't want them public known.

**Comment by Glassertje** [comment]
I also send a support ticket before i made this post. 864038 Is it an idea that i send the debug log to this ticket? Because i have seen that my domains are in the debug log and want to keep it private as it can.

**Comment by Versty** [comment]
@Glassertje Hi! 
Try adding these servers separately. Will both servers be added successfully?

**Comment by Glassertje** [comment]
I tried everything.

24 jan 2024 11:02:05 Diana ***@***.***>:

**Comment by Glassertje** [comment]
I tried that again. If 1 add 1 custom DNS i can add it. If i want to add the second than i can't add it and get the red message.

Edit: Just deleted the custom DNS and added it again, and now again it won't work. Getting again the red message that server don't respond or exist. After that deleted the custom DNS again and try it again, and i can add it and works.

**Comment by Versty** [comment]
@Glassertje Thank you for details. 
We would like to reproduce this issue on our side. 
Please provide both problematic dns servers to our mail `devteam@adguard.com`, mention the `5183` issue number in the subject.

**Comment by Glassertje** [comment]
@Versty Email send. Thank you for the help.

**Comment by Versty** [comment]
@Glassertje We have received the email from you and are currently investigating this issue.

**Comment by Glassertje** [comment]
@Versty a little update. Sins my last message i tested 1 custom DNS in version 4.3.1. Yesterday again i had no internet. Took about a minute before my internet was back, when i opent a app. For now i went back to 4.2.0.

**Comment by Versty** [comment]
@Glassertje Thanks to you we have found the root cause. This issue will be fixed in the next updates. 
You can track the status of the fix in https://github.com/AdguardTeam/DnsLibs/issues/217

**Comment by Glassertje** [comment]
> @Glassertje Thanks to you we have found the root cause. This issue will be fixed in the next updates. You can track the status of the fix in [AdguardTeam/DnsLibs#217](https://github.com/AdguardTeam/DnsLibs/issues/217)

Thank you for letting me know and glad that it will be fixed.

**Comment by sfionov** [comment]
The fix is available in the latest Android nightly, and will be included into upcoming 4.4 beta.

**Comment by Glassertje** [comment]
Thank you for letting me know and for the good work you guys do.

**Comment by Glassertje** [comment]
@Versty  I just noticed that this issue is still not complete fixed. DoH and DoQ is working in Adguard Android 4.4 Beta1 with my 2 AdGuard Home servers.

If i want to add both AdGuard Home servers with DoT in AdGuard Android, i still get the message the the server is not existing. I use AdGuard Android 4.4 Beta1. 

I can setup both DoT servers if i install stable AdGuard Android 4.3.1, if then update to latest Beta1, they still work. If i delete them i can't add them, becourse of the message the server don't exist. But the problem in 4.3.1 was that i could not add 2 DoH servers. and they stopt working after a while. Don't know if the DoT servers keep working after a while. I had to stop iusing it for a while, biut everything is up and running angain. For now i use my DoQ serer adresses.

You may test my servers if you want. The adresses are still the same, as that i send via email.
