### ISSUE TITLE
Few translations are still remains English

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#5418]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

V4.7 nightly 5

### Environment

- OS version: Android 8.1.0
- Device: Samsung J7 Prime

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. For AMP, go to the `Userscrip` section and you will see.
2. For AdGuard DNS filter, go to the `DNS filters` sections and you will see.

### Expected Behavior

Strings should be localizable for languages. If strings are missed at the Crowdin, you can add those.

### Actual Behavior

Disable AMP and AdGuard DNS filter strings are still remains as English for months probably. Not sure if strings are missed at the Crowdin.

### Screenshots

<details><summary>Disable AMP</summary>

![String](https://github.com/user-attachments/assets/13761db3-9d28-45cd-853f-e8b72f054381)
</details>

<details><summary>AG DNS Filter</summary>

![String1](https://github.com/user-attachments/assets/d2a249fb-1b99-4827-9cc4-9287bf33dbe3)
</details>

**Comment by Versty** [comment]
@gork7777 Thank you! Will be improved in future versions.

**Comment by gork7777** [comment]
Also this one is missing too
![Bugg](https://github.com/user-attachments/assets/f255dd51-c8ba-45b7-851c-7f71135752c7)

**Comment by artemiv4nov** [comment]
I've just checked on the last "Disable AMP" version and translations are available! Please update your userscripts.

**Comment by gork7777** [comment]
Again I checked in v4.7 nightly 24 and only `Disable AMP` is still remains in English, other strings are fixed.

**Comment by gork7777** [comment]
@Versty @artemiv4nov I've checked in v4.7 nightly 28 but still have problem for Turkish language.

**Comment by Versty** [comment]
@gork7777 Can confirm, some translations are still missing in 4.7 nightly 43. Will be resolved a bit later.
