### ISSUE TITLE
AGa crashes when Android WebView unloads

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#5521]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7n57

### Environment

- OS version: Android 12
- Device: 1+ N200 5g

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Legitimate URL Shortener, Peter Lowe's Blocklist

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, I don't care about cookies, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter, CJX's Annoyances List, Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish GDPR-Cookies Filters, RU AdList - Counters

### Other

AdGuard Experimental filter

### Which DNS server do you use?

Open DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Load AGa
2. Wait for OS to or manually kill Android Webview

### Expected Behavior

- AGa shouldn't load Android Webview unless Private Browser is currently being used, & should unload it immediately after
- AGa shouldn't crash if Webview is killed

### Actual Behavior

- AGa constantly runs Webview
- If Webview is killed, all of AGa goes with it

### Screenshots

No screenshots possible?  Just the disappearance of AGa suddenly when Webview's killed.

### Additional Information

This might be a real solution for @snhv's #5518.

**Comment by Versty** [comment]
@TPS Thank you for reporting! 
This problem reproduces on our side as well. The crash will be fixed soon. 

Unfortunately, the Webview start is currently can not be moved to the Private Browser start phase due to technical reasons.

**Comment by TPS** [comment]
> Unfortunately, the Webview start is currently can not be moved to the Private Browser start phase due to technical reasons. 

So how's this planning to be fixed?  The OS may unload WebView anytime it wants & perceives it's not actively being used.  If it does, will Private Browsing cease to work until AGa itself restarts?  This seems… weird.

**Comment by TPS** [comment]
@Deneno I just installed v4.7n59, which changelog says fixes this.  Unfortunately, it fails the exact same way as above.  What now?

**Comment by maxikuzmin** [comment]
@TPS please update to RC 2, version will be released soon, we fixed this bug

**Comment by TPS** [comment]
@Deneno No, both v4.7n60 & v4.7rc2 still crash identically — this is _not_ fixed!

**Comment by TPS** [comment]
@Numci @maxikuzmin @Versty When should we expect an actual fix to test?
