### ISSUE TITLE
Adguard closes if you swipe it with 'No icon' notification setting

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#561]
It only happens after 2.5.196 update. In older versions (2.1.359) this was not an issue, Adguard continued to work.

User has rooted device and uses proxy mode.

Original thread:
https://forum.adguard.com/index.php?threads/10065

**Comment by ameshkov** [comment]
@Revertron that's because of me turning off "Dummy" intent thing for Android L. We should also check for notification type , not just for Android version.

**Comment by Revertron** [comment]
Maybe we can do dummy intent for service, not for activity?

**Comment by ameshkov** [comment]
No idea, you should test it on KitKat

**Comment by ameshkov** [comment]
Fixed

**Comment by Hobbix** [comment]
Not fixed.
Not fixed, more info here: https://forum.adguard.com/index.php?threads/%D0%9E%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D0%B5%D1%82%D1%81%D1%8F-adguard-2-5-196.10065/page-2#post-88774
